### ISSUE TITLE
Get and Display Quote from Quotable API

### ISSUE THREAD

**Issue by KrisSmith7** [KrisSmith7/cryptoquotes#1]
Working with quotable api to return a quote to page.

**Comment by KrisSmith7** [comment]
As of 11/18, "data.content" is not returning the quote to the page.

**Comment by DSiedlarz90** [comment]
Quote is correctly being grabbed and displayed on page as of now. I also got the quotable working with Coinbase API to properly populate based on gain/loss after user input.
